version: '3.3'

services:

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/etc/prometheus/data'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always
    extra_hosts: ["host.docker.internal:host-gateway"]
    depends_on:
      - cadvisor
      - node-exporter

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    extra_hosts: ["host.docker.internal:host-gateway"]
    volumes:
      - ./alertmanager:/etc/alertmanager
    restart: always
    command:
      --config.file=/etc/alertmanager/alertmanager.yml --log.level=debug
    deploy:
      mode: global

  node-exporter:
    image: prom/node-exporter:latest
    container_name: monitoring_node_exporter
    restart: unless-stopped
    extra_hosts: ["host.docker.internal:host-gateway"]
    ports:
      - 9100:9100

  cadvisor:
    image: gcr.io/cadvisor/cadvisor-arm64@sha256:b090fb3a028f8c5d6ce4464c057b2ad8fae62b002d8f9c10dd46723f46af7679
    privileged: true
    container_name: cadvisor
    extra_hosts: ["host.docker.internal:host-gateway"]
    ports:
    - 8084:8080
    extra_hosts: ["host.docker.internal:host-gateway"]
    volumes:
    - /:/rootfs:ro
    - /var/run/docker.sock:/var/run/docker.sock:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    - /etc/machine-id:/etc/machine-id:ro
    depends_on:
      - redis

  grafana:
    image: grafana/grafana-enterprise
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/log:/var/log/
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    restart: always
    extra_hosts: ["host.docker.internal:host-gateway"]
    environment:
      GF_RENDERING_SERVER_URL: http://host.docker.internal:8081/render
      GF_RENDERING_CALLBACK_URL: http://host.docker.internal:3000/
      GF_LOG_FILTERS: rendering:debug
  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8082:8081
    extra_hosts: ["host.docker.internal:host-gateway"]

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    extra_hosts: ["host.docker.internal:host-gateway"]

  redis-exporter:
    image: oliver006/redis_exporter
    command: -redis.addr redis://redis:6379
    ports:
      - 9121:9121
    extra_hosts: ["host.docker.internal:host-gateway"]