groups:
  - name: Memory-usage
    rules:
      - alert: "High memory usage"
        expr: ceil((((node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes) * 100)) > 80
        labels:
          severity: "critical"
        annotations:
          title: "Memory Usage"
          description: "Memory usage threshold set to `80%`."
          summary: "Memory usage is `{{humanize $value}}%`"
          host: "{{$labels.instance}}"
  - name: AllInstances
    rules:
      - alert: InstanceDown
        # Condition for alerting
        expr: up == 0
        for: 1m
        # Annotation - additional informational labels to store more information
        annotations:
          title: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."
          summary: "Instance {{ $labels.instance }} went down"
          host: "{{$labels.instance}}"
        # Labels - additional labels to be attached to the alert
        labels:
          severity: "critical"
