{
 "title": "Docker Host & Container Overview",
 "description": "A simple overview of the most important Docker host and container metrics. (cAdvisor/Prometheus)",
 "tags": [
  "Docker",
  "Containers"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "30s, 1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Network Traffic on Node",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{name=~\".+\"}[$interval]))",
     "legendFormat": "Containers"
    }
   ]
  },
  {
   "title": "CPU Usage on Node",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total[$interval])) * 100",
     "legendFormat": "host"
    }
   ]
  },
  {
   "title": "Free and Used Disk Space on Node in GB",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((node_filesystem_size_bytes - node_filesystem_free_bytes)) / (1024 * 1024 * 1024)",
     "legendFormat": "Used Disk Space"
    },
    {
     "expr": "Avg(node_filesystem_avail_bytes) / (1024 * 1024 * 1024)",
     "legendFormat": "Free Disk Space"
    }
   ]
  },
  {
   "title": "Available Memory on Node in GB",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"host.docker.internal:9100\", job=\"node-exporter\"} / (1024 * 1024 * 1024)"
    }
   ]
  },
  {
   "title": "CPU Usage per Container (Stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[$interval])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Cached Memory per Container (Stacked)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_cache{name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "cadvisor_version_info",
     "legendFormat": "cAdvisor Version: {{cadvisorVersion}}"
    },
    {
     "expr": "prometheus_build_info",
     "legendFormat": "Prometheus Version: {{version}}"
    },
    {
     "expr": "node_exporter_build_info",
     "legendFormat": "Node-Exporter Version: {{version}}"
    },
    {
     "expr": "cadvisor_version_info",
     "legendFormat": "Docker Version: {{dockerVersion}}"
    },
    { "expr": "cadvisor_version_info", "legendFormat": "Host OS Version: {{osVersion}}" },
    {
     "expr": "cadvisor_version_info",
     "legendFormat": "Host Kernel Version: {{kernelVersion}}"
    }
   ]
  }
 ]
}